
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.63
distribution_type: module
version: 1.01
name: prefork
author: Adam Kennedy, L<http://ali.as/>, cpan@ali.as
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.10
  perl: 5.005
abstract: Optimized module loading for forking or non-forking processes
