name: prefork
version: 1.00
abstract: Optimized module loading for forking or non-forking processes
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  Scalar::Util: 1.10
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
